### ISSUE TITLE
The tag does not exist 

### ISSUE THREAD

**Issue by python36** [ostera/ws#2]
Hi. The file says that you need to specify the tag for installation:
```
{ws, {git, "https://github.com/ostera/ws", {tag, "0.1.0"}}}
```
But this tag does not exist and rebar3 exit with an error. Please create tag or update README.

**Comment by leostera** [comment]
Hello, this library is unfinished and unmaintained! 😱

**Comment by python36** [comment]
:confused: Please mention this in the README and remove the Installation part.

**Comment by leostera** [comment]
Happy to take pull requests for this :) closing the issue for now.

**Comment by python36** [comment]
maybe you need to delete the repository?
